name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: markyin0707/social-readme@master
        with:
          blog_rss_link: https://www.markyin.cn/atom.xml     #your blog rss link
          blog_limit: 5 # blog数量
          douban_name: markyin0707    
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated social rss by social-readme # commit说明
